"""
Conversational Planner — LangGraph graph implementation.

Graph topology:
    START → plan_node → gather_node → propose_node
                             ↑              |
                             └──────────────┘  (needs_more_data and gather_iterations < 1)
                                           ↓
                                   human_review_node → execute_node → END
"""
from __future__ import annotations

import asyncio
import json
import uuid
from datetime import date, timedelta
from typing import Any

import aiosqlite
from langchain_core.messages import AIMessage, HumanMessage, SystemMessage
from langchain_google_genai import ChatGoogleGenerativeAI
from langgraph.checkpoint.memory import MemorySaver
from langgraph.graph import END, START, StateGraph
from langgraph.types import interrupt
from typing_extensions import TypedDict

from ..config import GEMINI_API_KEY, GEMINI_MODEL, PLAN_MD_PATH
from ..db.connection import get_db
from ..db.queries import insert_event, reschedule_task, upsert_system_state
from ..tools.planner_tools import (
    check_capacity,
    get_current_plan,
    get_resource_progress,
    get_task_stats,
    get_tasks_by_date,
    rewrite_plan,
    update_tasks,
)

# ---------------------------------------------------------------------------
# State
# ---------------------------------------------------------------------------


class PlannerState(TypedDict):
    messages: list               # Full conversation history (HumanMessage / AIMessage)
    user_input: str
    intent: str                  # Intent description parsed by plan_node
    tools_needed: list[str]      # Read tools that plan_node decided to call
    gathered_data: dict          # Data collected by gather_node
    gather_iterations: int       # Back-track counter; capped at 1
    proposal: dict | None        # Change proposal generated by propose_node
    needs_more_data: bool        # Whether propose_node wants to gather more
    user_confirmed: bool | None
    pending_changes: list        # Write operations to be executed


# ---------------------------------------------------------------------------
# LLM factory
# ---------------------------------------------------------------------------

def _llm() -> ChatGoogleGenerativeAI:
    return ChatGoogleGenerativeAI(
        model=GEMINI_MODEL,
        google_api_key=GEMINI_API_KEY,
        temperature=0.2,
    )


# ---------------------------------------------------------------------------
# System prompts
# ---------------------------------------------------------------------------

_PLAN_SYSTEM_PROMPT = """你是 MalDaze 学习助手的对话规划器，负责理解用户的学习管理意图并决定需要哪些数据来制定回应方案。

## 减载意图识别

以下表达均属于减载意图（用户希望降低当前学习负荷）：
- "我想摆了" / "今天摆了" / "想摆一下" / "想摆一周"
- "撑不住了" / "坚持不住了" / "扛不住了"
- "今天不行" / "今天没状态" / "状态很差"
- "放松一下" / "休息一下" / "歇一歇"
- "累了" / "太累了" / "很累" / "疲了"
- 以及任何表达疲劳、倦怠、希望减少学习任务的语义

识别到减载意图时，intent 应包含 "load_reduction"。

## 可用读工具

- get_tasks_by_date: 获取指定日期的任务列表（含 id、title、target_minutes、scheduled_date），需要 date 参数（ISO 格式 YYYY-MM-DD）。**当用户要求对某天的任务做任何变更时，必须先调用此工具获取 task_id。**
- get_current_plan: 读取 plan.md 全文
- get_task_stats: 获取任务完成统计（period: today/this_week/last_week）
- get_resource_progress: 获取资料进度（需要 resource_id）
- check_capacity: 查看时间段内的剩余容量（需要 start/end 日期）

## 输出格式

请以 JSON 回复，格式如下：
{
  "intent": "<意图描述，中文>",
  "tools_needed": ["tool_name", ...],
  "tool_params": {
    "get_tasks_by_date": {"date": "YYYY-MM-DD"},
    "get_task_stats": {"period": "today"},
    "check_capacity": {"start": "YYYY-MM-DD", "end": "YYYY-MM-DD"},
    "get_resource_progress": {"resource_id": 1}
  }
}

tools_needed 只列出真正需要调用的工具名称。若不需要任何数据，tools_needed 为空列表。
"""

_PROPOSE_SYSTEM_PROMPT = """你是 MalDaze 学习助手，负责根据用户意图和已收集的数据生成具体的变更提案。

## 减载意图处理规则

当检测到减载意图时，你应该：
1. 将今日或近期任务推迟（reschedule）到未来空档日期
2. 降低未完成任务的优先级
3. 如果用户说"摆一周"，则对未来7天内的任务作相应调整

## 输出格式

请以 JSON 回复，格式如下：
{
  "description": "<用中文描述这个提案的核心内容>",
  "changes": [
    {"action": "reschedule", "task_id": 1, "scheduled_date": "YYYY-MM-DD"},
    {"action": "update", "task_id": 2, "priority": 1}
  ],
  "affects_deadline": true/false,
  "summary_for_user": "<展示给用户的简洁摘要，中文>",
  "needs_more_data": false
}

如果现有数据不足以制定合理方案，将 needs_more_data 设为 true，并在 description 中说明缺少什么信息。
changes 为空列表表示无需变更（例如纯粹的信息查询）。
"""


# ---------------------------------------------------------------------------
# Graph nodes
# ---------------------------------------------------------------------------

async def plan_node(state: PlannerState) -> dict:
    """Parse user intent and decide which read tools to call."""
    llm = _llm()

    history = list(state.get("messages", []))
    history.append(HumanMessage(content=state["user_input"]))

    today = date.today().isoformat()
    week_end = (date.today() + timedelta(days=6)).isoformat()

    system_content = _PLAN_SYSTEM_PROMPT + f"\n\n今天的日期是 {today}，本周结束日期是 {week_end}。"

    response = await llm.ainvoke(
        [SystemMessage(content=system_content)] + history
    )

    raw = response.content.strip()
    # Strip markdown code fences if present
    if raw.startswith("```"):
        raw = raw.split("```")[1]
        if raw.startswith("json"):
            raw = raw[4:]
    raw = raw.strip()

    try:
        parsed = json.loads(raw)
    except json.JSONDecodeError:
        parsed = {
            "intent": raw,
            "tools_needed": ["get_current_plan", "get_task_stats"],
            "tool_params": {"get_task_stats": {"period": "today"}},
        }

    updated_messages = list(state.get("messages", []))
    updated_messages.append(HumanMessage(content=state["user_input"]))

    return {
        "messages": updated_messages,
        "intent": parsed.get("intent", ""),
        "tools_needed": parsed.get("tools_needed", []),
        # Stash tool params temporarily in gathered_data as "__params__"
        "gathered_data": {"__params__": parsed.get("tool_params", {})},
        "gather_iterations": state.get("gather_iterations", 0),
    }


async def gather_node(state: PlannerState) -> dict:
    """Call required read tools in parallel and merge results."""
    tools_needed: list[str] = state.get("tools_needed", [])
    existing_data: dict = dict(state.get("gathered_data", {}))
    params: dict = existing_data.pop("__params__", {})

    today = date.today()
    week_end = (today + timedelta(days=6)).isoformat()
    today_str = today.isoformat()

    async def _call_tool(name: str) -> tuple[str, Any]:
        async with get_db() as db:
            if name == "get_tasks_by_date":
                p = params.get("get_tasks_by_date", {})
                result = await get_tasks_by_date(db, p.get("date", today_str))
            elif name == "get_current_plan":
                result = await get_current_plan(db, PLAN_MD_PATH)
            elif name == "get_task_stats":
                p = params.get("get_task_stats", {})
                result = await get_task_stats(db, p.get("period", "today"))
            elif name == "get_resource_progress":
                p = params.get("get_resource_progress", {})
                rid = p.get("resource_id")
                if rid is None:
                    result = {"error": "resource_id not provided"}
                else:
                    result = await get_resource_progress(db, int(rid))
            elif name == "check_capacity":
                p = params.get("check_capacity", {})
                result = await check_capacity(
                    db,
                    p.get("start", today_str),
                    p.get("end", week_end),
                )
            else:
                result = {"error": f"unknown tool: {name}"}
        return name, result

    if tools_needed:
        results = await asyncio.gather(*[_call_tool(t) for t in tools_needed])
        gathered: dict = {name: data for name, data in results}
    else:
        gathered = {}

    gathered.update(existing_data)

    return {
        "gathered_data": gathered,
        "gather_iterations": state.get("gather_iterations", 0) + 1,
    }


async def propose_node(state: PlannerState) -> dict:
    """Generate a change proposal based on gathered data and user intent."""
    llm = _llm()

    today = date.today().isoformat()
    context = {
        "today": today,
        "intent": state.get("intent", ""),
        "gathered_data": state.get("gathered_data", {}),
    }

    history = list(state.get("messages", []))
    context_msg = HumanMessage(
        content=f"[系统上下文]\n{json.dumps(context, ensure_ascii=False, indent=2)}"
    )

    response = await llm.ainvoke(
        [SystemMessage(content=_PROPOSE_SYSTEM_PROMPT)] + history + [context_msg]
    )

    raw = response.content.strip()
    if raw.startswith("```"):
        raw = raw.split("```")[1]
        if raw.startswith("json"):
            raw = raw[4:]
    raw = raw.strip()

    try:
        parsed = json.loads(raw)
    except json.JSONDecodeError:
        parsed = {
            "description": raw,
            "changes": [],
            "affects_deadline": False,
            "summary_for_user": raw,
            "needs_more_data": False,
        }

    needs_more = bool(parsed.get("needs_more_data", False))
    # Force-stop infinite gather loop
    if state.get("gather_iterations", 0) >= 1:
        needs_more = False

    proposal = {
        "description": parsed.get("description", ""),
        "changes": parsed.get("changes", []),
        "affects_deadline": parsed.get("affects_deadline", False),
        "summary_for_user": parsed.get("summary_for_user", parsed.get("description", "")),
    }

    # Pre-compute pending_changes via update_tasks (dry run)
    pending: list = []
    if proposal["changes"]:
        async with get_db() as db:
            result = await update_tasks(db, proposal["changes"])
            pending = result.get("pendingChanges", [])

    return {
        "proposal": proposal,
        "needs_more_data": needs_more,
        "pending_changes": pending,
    }


def route_after_propose(state: PlannerState) -> str:
    """Route back to gather if more data is needed (max 1 extra iteration)."""
    if state.get("needs_more_data") and state.get("gather_iterations", 0) < 1:
        return "gather"
    proposal = state.get("proposal") or {}
    if not proposal.get("changes"):
        return "respond"
    return "human_review"


async def respond_node(state: PlannerState) -> dict:
    """Return a conversational text reply when there are no changes to confirm."""
    proposal = state.get("proposal") or {}
    text = proposal.get("summary_for_user") or proposal.get("description") or "好的，已了解。"
    msg = AIMessage(content=text)
    return {"messages": state.get("messages", []) + [msg]}


async def human_review_node(state: PlannerState) -> dict:
    """Gate node: graph pauses BEFORE this node via interrupt_before=["human_review"].
    When confirm_proposal() resumes with {"user_confirmed": bool}, that value is
    already applied to state before this node runs — nothing to do here."""
    return {}


async def execute_node(state: PlannerState) -> dict:
    """Execute approved changes or return a cancellation message."""
    if not state.get("user_confirmed"):
        cancel_msg = AIMessage(content="好的，已取消变更，保持现有计划不变。")
        return {"messages": state.get("messages", []) + [cancel_msg]}

    pending: list = state.get("pending_changes", [])
    applied: list[dict] = []

    plan_content_override: str | None = None

    async with get_db() as db:
        for change in pending:
            action = change.get("action")
            task_id = change.get("task_id")

            if action == "reschedule" and task_id:
                new_date_str = change.get("scheduled_date", "")
                try:
                    new_date = date.fromisoformat(new_date_str)
                    await reschedule_task(db, int(task_id), new_date)
                    applied.append(change)
                except (ValueError, TypeError):
                    pass

            elif action == "update" and task_id:
                fields: list[str] = []
                values: list[Any] = []
                if "priority" in change:
                    fields.append("priority = ?")
                    values.append(change["priority"])
                if "scheduled_date" in change:
                    fields.append("scheduled_date = ?")
                    values.append(change["scheduled_date"])
                if fields:
                    values.append(int(task_id))
                    await db.execute(
                        f"UPDATE tasks SET {', '.join(fields)} WHERE id = ?",
                        values,
                    )
                    await db.commit()
                    applied.append(change)

        proposal = state.get("proposal") or {}
        if plan_content_override:
            await rewrite_plan(db, PLAN_MD_PATH, plan_content_override)

        await insert_event(db, "plan_updated", {
            "triggered_by": "conversational_planner",
            "changes_applied": len(applied),
            "intent": state.get("intent", ""),
        })

    summary = proposal.get("summary_for_user", f"已应用 {len(applied)} 项变更。")
    done_msg = AIMessage(content=f"{summary}\n\n（共应用 {len(applied)} 项变更）")

    return {"messages": state.get("messages", []) + [done_msg]}


# ---------------------------------------------------------------------------
# Graph assembly
# ---------------------------------------------------------------------------

def create_planner_graph():
    """Build and compile the conversational planner graph with MemorySaver."""
    builder = StateGraph(PlannerState)

    builder.add_node("plan", plan_node)
    builder.add_node("gather", gather_node)
    builder.add_node("propose", propose_node)
    builder.add_node("respond", respond_node)
    builder.add_node("human_review", human_review_node)
    builder.add_node("execute", execute_node)

    builder.add_edge(START, "plan")
    builder.add_edge("plan", "gather")
    builder.add_edge("gather", "propose")
    builder.add_conditional_edges(
        "propose",
        route_after_propose,
        {"gather": "gather", "respond": "respond", "human_review": "human_review"},
    )
    builder.add_edge("respond", END)
    builder.add_edge("human_review", "execute")
    builder.add_edge("execute", END)

    memory = MemorySaver()
    return builder.compile(checkpointer=memory, interrupt_before=["human_review"])


# Singleton graph (compiled once)
_graph = None


def _get_graph():
    global _graph
    if _graph is None:
        _graph = create_planner_graph()
    return _graph


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

async def start_conversation(user_input: str, thread_id: str | None = None) -> dict:
    """Start or continue a conversation thread.

    Returns:
        {
            "thread_id": str,
            "proposal": dict | None,   # present when the graph reaches human_review
            "response": str | None,    # present for non-proposal replies
        }
    """
    if thread_id is None:
        thread_id = str(uuid.uuid4())

    graph = _get_graph()
    config = {"configurable": {"thread_id": thread_id}}

    initial_state: PlannerState = {
        "messages": [],
        "user_input": user_input,
        "intent": "",
        "tools_needed": [],
        "gathered_data": {},
        "gather_iterations": 0,
        "proposal": None,
        "needs_more_data": False,
        "user_confirmed": None,
        "pending_changes": [],
    }

    # stream until interrupt or completion
    final_state: dict = {}
    async for event in graph.astream(initial_state, config=config):
        final_state = event

    # After streaming, check current snapshot
    snapshot = graph.get_state(config)
    current = snapshot.values if snapshot else {}

    proposal = current.get("proposal")
    pending_tasks = snapshot.next if snapshot else []

    if pending_tasks and "human_review" in pending_tasks:
        return {
            "thread_id": thread_id,
            "proposal": proposal,
            "response": None,
        }

    # Graph ran to completion (no changes needed or already done)
    messages = current.get("messages", [])
    last_ai = next(
        (m.content for m in reversed(messages) if isinstance(m, AIMessage)),
        "好的，我已处理完您的请求。",
    )
    return {
        "thread_id": thread_id,
        "proposal": None,
        "response": last_ai,
    }


async def confirm_proposal(thread_id: str, confirmed: bool) -> dict:
    """Resume the graph after user confirms or rejects the proposal.

    Returns:
        {
            "thread_id": str,
            "status": "applied" | "cancelled",
            "changes_applied": int | None,
        }
    """
    graph = _get_graph()
    config = {"configurable": {"thread_id": thread_id}}

    # With interrupt_before=["human_review"], resume requires:
    # 1. update_state to inject the user's decision into the paused state
    # 2. astream(None, config) to continue execution from the interrupt point
    await graph.aupdate_state(config, {"user_confirmed": confirmed}, as_node="human_review")

    final_state: dict = {}
    async for event in graph.astream(None, config=config):
        final_state = event

    snapshot = graph.get_state(config)
    current = snapshot.values if snapshot else {}
    pending = current.get("pending_changes", [])

    if confirmed:
        return {
            "thread_id": thread_id,
            "status": "applied",
            "changes_applied": len(pending),
        }
    return {
        "thread_id": thread_id,
        "status": "cancelled",
        "changes_applied": None,
    }
